[package]
name = "jaster"
version = "1.0.10"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rodio = "0.21"
rdev = "0.5"
evdev = "0.13"
libc = "0.2.189"
udev = "0.9.3"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
colored = "3"