name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            pkg-config

      - name: Build
        run: cargo build --release

      - name: Rename binary
        run: |
          cp target/release/jaster jaster-linux-x86_64

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: jaster-linux-x86_64